# Generated by Django 3.2.6 on 2021-10-01 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='vimeo_embed_url',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='vimeo_view_url',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
