# Generated by Django 3.2.6 on 2021-10-07 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_auto_20211001_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='vimeo_embed_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='vimeo_view_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
