# Generated by Django 3.2.6 on 2021-10-09 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0004_video_vimoe_secondary_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='vimoe_secondary_id',
            new_name='vimeo_secondary_id',
        ),
    ]
