# Generated by Django 3.2.6 on 2021-10-09 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0005_rename_vimoe_secondary_id_video_vimeo_secondary_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='vimeo_secondary_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
