# Generated by Django 3.2.6 on 2021-10-29 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0007_auto_20211025_1924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='length',
        ),
    ]
