# Generated by Django 3.2.6 on 2021-10-29 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0008_remove_video_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='length',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
