# Generated by Django 3.2.6 on 2021-10-29 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0048_auto_20211008_1219'),
        ('media', '0009_video_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='correct_answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='problems.correctanswer'),
        ),
    ]
