# Generated by Django 3.2.6 on 2021-11-03 12:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0013_auto_20211103_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='file',
            field=models.FileField(upload_to='pdf/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AlterField(
            model_name='svg',
            name='image',
            field=models.FileField(upload_to='svg/', validators=[django.core.validators.FileExtensionValidator(['svg'])]),
        ),
    ]
