# Generated by Django 3.2.6 on 2022-02-25 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0014_auto_20211103_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='vimeo_thumbnail_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
