# Generated by Django 3.2.6 on 2022-03-19 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0015_video_vimeo_thumbnail_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_dark',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
