# Generated by Django 3.2.6 on 2021-11-22 18:00

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shopify_models', '0004_rename_template_sufix_template_template_suffix'),
        ('problems', '0050_alter_answerchoice_choice_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('shopify_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shopify_models.product')),
            ],
        ),
        migrations.CreateModel(
            name='CourseChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.course')),
            ],
        ),
        migrations.CreateModel(
            name='CourseLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.coursechapter')),
            ],
            managers=[
                ('lessons', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='CourseQuizz',
            fields=[
                ('courselesson_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='courses.courselesson')),
                ('description', models.TextField()),
            ],
            bases=('courses.courselesson',),
            managers=[
                ('lessons', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='CourseStepByStepProblem',
            fields=[
                ('courselesson_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='courses.courselesson')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.problem')),
            ],
            bases=('courses.courselesson',),
            managers=[
                ('lessons', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='CourseProblemWithVideo',
            fields=[
                ('courselesson_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='courses.courselesson')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.problem')),
            ],
            bases=('courses.courselesson',),
            managers=[
                ('lessons', django.db.models.manager.Manager()),
            ],
        ),
    ]
