# Generated by Django 3.2.6 on 2021-11-27 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursechapter',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='courselesson',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='courseproblemwithvideo',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='coursequizz',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='coursestepbystepproblem',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelManagers(
            name='courselesson',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='courseproblemwithvideo',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='coursequizz',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='coursestepbystepproblem',
            managers=[
            ],
        ),
        migrations.RenameField(
            model_name='courselesson',
            old_name='course',
            new_name='chapter',
        ),
        migrations.AddField(
            model_name='coursechapter',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='courselesson',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='courselesson',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_courses.courselesson_set+', to='contenttypes.contenttype'),
        ),
    ]
