# Generated by Django 3.2.6 on 2021-11-27 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20211127_0015'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseProblemWithVideo',
        ),
    ]
