# Generated by Django 3.2.6 on 2021-11-27 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0050_alter_answerchoice_choice_text'),
        ('courses', '0003_delete_courseproblemwithvideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseProblemVideo',
            fields=[
                ('courselesson_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='courses.courselesson')),
                ('description', models.TextField()),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.problem')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('courses.courselesson',),
        ),
    ]
