# Generated by Django 3.2.6 on 2021-12-02 19:40

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_courseproblemvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseproblemvideo',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
