# Generated by Django 3.2.6 on 2021-12-02 19:45

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_courseproblemvideo_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseproblemvideo',
            name='rich_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
