# Generated by Django 3.2.6 on 2021-12-02 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_courseproblemvideo_rich_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseproblemvideo',
            name='content',
        ),
    ]
