# Generated by Django 3.2.6 on 2022-07-19 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0069_log_entry_jsonfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseBuilderPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('course_title', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Course Page',
                'verbose_name_plural': 'Course Page',
            },
            bases=('wagtailcore.page',),
        ),
    ]
