# Generated by Django 3.2.6 on 2022-07-19 17:36

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagmin', '0002_auto_20220719_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursepage',
            name='content',
            field=wagtail.fields.StreamField([('course_chapters', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(help_text='Title that will be displayed on web', required=True)), ('admin_title', wagtail.blocks.CharBlock(help_text='Title that will be displayed only in admin', required=True)), ('lessons', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('title', wagtail.blocks.TextBlock(max_length=100, required=True)), ('lesson_problem_solution', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(help_text='Title that will be displayed on web', required=True)), ('admin_title', wagtail.blocks.CharBlock(help_text='Title that will be displayed only in admin', required=True)), ('lessons', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('title', wagtail.blocks.TextBlock(max_length=100, required=True))])))]))])))]))], blank=True, null=True, use_json_field=None),
        ),
    ]
