# Generated by Django 3.2.6 on 2022-07-19 18:17

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagmin', '0003_alter_coursepage_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursepage',
            name='content',
        ),
        migrations.CreateModel(
            name='CourseChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('lessons', wagtail.fields.StreamField([('lesson_problem_solution', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(help_text='Title that will be displayed on web', required=True)), ('admin_title', wagtail.blocks.CharBlock(help_text='Title that will be displayed only in admin', required=True)), ('lessons', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('title', wagtail.blocks.TextBlock(max_length=100, required=True))])))])), ('lesson_quiz', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(help_text='Title that will be displayed on web', required=True)), ('admin_title', wagtail.blocks.CharBlock(help_text='Title that will be displayed only in admin', required=True)), ('lessons', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('title', wagtail.blocks.TextBlock(max_length=100, required=True))])))])), ('lesson_video', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(help_text='Title that will be displayed on web', required=True)), ('admin_title', wagtail.blocks.CharBlock(help_text='Title that will be displayed only in admin', required=True)), ('lessons', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('title', wagtail.blocks.TextBlock(max_length=100, required=True))])))])), ('lesson_page_content', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(help_text='Title that will be displayed on web', required=True)), ('admin_title', wagtail.blocks.CharBlock(help_text='Title that will be displayed only in admin', required=True)), ('lessons', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('title', wagtail.blocks.TextBlock(max_length=100, required=True))])))])), ('lesson_interactive_map', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(help_text='Title that will be displayed on web', required=True)), ('admin_title', wagtail.blocks.CharBlock(help_text='Title that will be displayed only in admin', required=True)), ('lessons', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('title', wagtail.blocks.TextBlock(max_length=100, required=True))])))]))], use_json_field=None)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='wagmin.coursepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
