// PROBLEMS
export const UPDATE_QUESTION_TEXT = 'UPDATE_QUESTION_TEXT';
export const UPDATE_QUESTION_IMAGE = 'UPDATE_QUESTION_IMAGE';
export const UPDATE_SUBQUESTION_TEXT = 'UPDATE_SUBQUESTION_TEXT';
export const UPDATE_ANSWER_CHOICE_TEXT = 'UPDATE_ANSWER_CHOICE_TEXT';
export const UPDATE_ANSWER_CHOICE_IMAGE = 'UPDATE_ANSWER_CHOICE_IMAGE';
export const UPDATE_PROBLEM_ORDER = 'UPDATE_PROBLEM_ORDER';
export const FETCH_PROBLEMS = 'FETCH_PROBLEMS';

// PREBLEMS VIEW TYPE
export const TOGGLE_EDITING = 'TOGGLE_EDITING'
export const TOGGLE_PRINT_PREVIEW = 'TOGGLE_PRINT_PREVIEW'

// FORM FIELDS
export const UPDATE_IMAGE_FIELDS = 'UPDATE_IMAGE_FIELDS'
export const UPDATE_QUESTION_FIELDS = 'UPDATE_QUESTION_FIELDS'
export const UPDATE_ANSWER_CHOICE_FIELDS = 'UPDATE_ANSWER_CHOICE_FIELDS'



export const TYPSET_MATHJAX = 'TYPSET_MATHJAX'

export const ADD_INPUT_FIELD = 'ADD_INPUT_FIELD'