# Generated by Django 3.2.6 on 2021-08-29 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0004_auto_20210829_0953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='subquestion',
        ),
        migrations.AddField(
            model_name='question',
            name='subquestion',
            field=models.ManyToManyField(related_name='_problems_question_subquestion_+', to='problems.Question'),
        ),
    ]
