# Generated by Django 3.2.6 on 2021-08-29 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0005_auto_20210829_1005'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subquestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('subquestion', models.ManyToManyField(related_name='_problems_subquestion_subquestion_+', to='problems.Subquestion')),
            ],
        ),
        migrations.AlterField(
            model_name='question',
            name='subquestion',
            field=models.ManyToManyField(to='problems.Subquestion'),
        ),
    ]
