# Generated by Django 3.2.6 on 2021-08-29 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0006_auto_20210829_1008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='subquestion',
        ),
        migrations.AddField(
            model_name='subquestion',
            name='main_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='problems.question'),
        ),
    ]
