# Generated by Django 3.2.6 on 2021-08-29 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0007_auto_20210829_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subquestion',
            name='subquestion',
            field=models.ManyToManyField(blank=True, related_name='_problems_subquestion_subquestion_+', to='problems.Subquestion'),
        ),
    ]
