# Generated by Django 3.2.6 on 2021-08-29 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0008_alter_subquestion_subquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='subquestion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='problems.question'),
        ),
        migrations.DeleteModel(
            name='Subquestion',
        ),
    ]
