# Generated by Django 3.2.6 on 2021-08-29 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0015_auto_20210829_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='shopify_page_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
