# Generated by Django 3.2.6 on 2021-08-29 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0018_problem_video_solution'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='vimeo',
            new_name='vimeo_id',
        ),
        migrations.RemoveField(
            model_name='video',
            name='name',
        ),
        migrations.RemoveField(
            model_name='video',
            name='vimeo_edit_link',
        ),
        migrations.RemoveField(
            model_name='video',
            name='vimeo_embed_link',
        ),
        migrations.RemoveField(
            model_name='video',
            name='vimeo_view_link',
        ),
    ]
