# Generated by Django 3.2.6 on 2021-08-29 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0020_video_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='vimeo_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
