# Generated by Django 3.2.6 on 2021-08-29 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0022_auto_20210829_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='problems.question'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='video_solution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='problems.video'),
        ),
    ]
