# Generated by Django 3.2.6 on 2021-09-01 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0024_auto_20210901_0919'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matura',
            options={'ordering': ['year']},
        ),
        migrations.AlterModelOptions(
            name='year',
            options={'ordering': ['-year']},
        ),
    ]
