# Generated by Django 3.2.6 on 2021-09-01 09:59

from django.db import migrations, models
import django.db.models.functions.comparison


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0025_auto_20210901_0935'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problem',
            options={'ordering': [django.db.models.functions.comparison.Cast('question__question_text', models.IntegerField()), 'order']},
        ),
    ]
