# Generated by Django 3.2.6 on 2021-09-05 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0027_auto_20210901_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='number',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
