# Generated by Django 3.2.6 on 2021-09-07 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0029_auto_20210907_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correctanswer',
            name='answer_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='correct_answer_choice', to='problems.answerchoice'),
        ),
        migrations.AlterField(
            model_name='correctanswer',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='correct_answer', to='problems.question'),
        ),
    ]
