# Generated by Django 3.2.6 on 2021-09-07 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0030_auto_20210907_1457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='correctanswer',
            name='answer_choice',
        ),
        migrations.AddField(
            model_name='correctanswer',
            name='correct_answer_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='problems.answerchoice'),
        ),
    ]
