# Generated by Django 3.2.6 on 2021-09-07 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0031_auto_20210907_1458'),
    ]

    operations = [
        migrations.RenameField(
            model_name='correctanswer',
            old_name='correct_answer_choice',
            new_name='answer_choice',
        ),
    ]
