# Generated by Django 3.2.6 on 2021-09-13 11:11

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0032_rename_correct_answer_choice_correctanswer_answer_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hint',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/static/images'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='problem',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problems', to='problems.section'),
        ),
        migrations.AlterField(
            model_name='section',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subject_name', to='problems.subject'),
        ),
    ]
