# Generated by Django 3.2.6 on 2021-09-13 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0033_auto_20210913_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hint',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
