# Generated by Django 3.2.6 on 2021-09-13 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0034_alter_hint_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerchoice',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
