# Generated by Django 3.2.6 on 2021-09-13 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0036_auto_20210913_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='matura',
            name='shopify_product_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='problems.question'),
        ),
    ]
