# Generated by Django 3.2.6 on 2021-09-13 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0037_auto_20210913_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='matura',
            name='shopify_product_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='shopify_page_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
