# Generated by Django 3.2.6 on 2021-09-14 14:18

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.comparison


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0038_auto_20210913_1423'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problem',
            options={'ordering': [django.db.models.functions.comparison.Cast('number', models.IntegerField())]},
        ),
        migrations.AlterField(
            model_name='image',
            name='answer_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='problems.answerchoice'),
        ),
    ]
