# Generated by Django 3.2.6 on 2021-09-20 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0039_auto_20210914_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='matura',
            name='vimeo_folder_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
