# Generated by Django 3.2.6 on 2021-09-30 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mature', '0001_initial'),
        ('media', '0001_initial'),
        ('skripte', '0001_initial'),
        ('problems', '0044_auto_20210929_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='answer_choice',
        ),
        migrations.RemoveField(
            model_name='image',
            name='question',
        ),
        migrations.RemoveField(
            model_name='matura',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='matura',
            name='term',
        ),
        migrations.RemoveField(
            model_name='matura',
            name='year',
        ),
        migrations.RemoveField(
            model_name='section',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='skripta',
            name='subject',
        ),
        migrations.AlterField(
            model_name='problem',
            name='matura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problems', to='mature.matura'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problems', to='skripte.section'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='skripta',
            field=models.ManyToManyField(blank=True, to='skripte.Skripta'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='skripte.subject'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='video_solution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='media.video'),
        ),
        migrations.DeleteModel(
            name='Equation',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='Matura',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
        migrations.DeleteModel(
            name='Skripta',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.DeleteModel(
            name='Term',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
        migrations.DeleteModel(
            name='Year',
        ),
    ]
