# Generated by Django 3.2.6 on 2021-10-07 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0047_auto_20211003_2114'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problem',
            options={'ordering': ['order', 'question']},
        ),
        migrations.AddField(
            model_name='problem',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
