# Generated by Django 3.2.6 on 2021-11-05 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0014_auto_20211103_1208'),
        ('problems', '0048_auto_20211008_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='correctanswer',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='media.image'),
        ),
    ]
