# Generated by Django 3.2.6 on 2021-10-08 11:08

from django.db import migrations, models
import django.db.models.functions.comparison


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0048_auto_20211007_1900'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problem',
            options={'ordering': [django.db.models.functions.comparison.Cast('number', models.IntegerField())]},
        ),
        migrations.RemoveField(
            model_name='problem',
            name='order',
        ),
    ]
