# Generated by Django 3.2.6 on 2021-09-30 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skripte', '0002_alter_subject_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
