# Generated by Django 3.2.6 on 2021-09-30 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mature', '0003_auto_20210930_2133'),
        ('skripte', '0003_alter_subject_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skripta',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mature.maturasubject'),
        ),
    ]
