# Generated by Django 3.2.6 on 2021-10-01 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skripte', '0004_alter_skripta_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skripta',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='skripte.subject'),
        ),
    ]
