# Generated by Django 3.2.6 on 2021-10-01 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skripte', '0005_alter_skripta_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='skripta',
            field=models.ManyToManyField(blank=True, to='skripte.Skripta'),
        ),
    ]
