# Generated by Django 3.2.6 on 2021-10-01 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skripte', '0006_section_skripta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='shopify_page_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
