# Generated by Django 3.2.6 on 2021-10-08 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skripte', '0008_alter_section_skripta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skripta',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='skripta',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
