# Generated by Django 3.2.6 on 2021-10-08 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skripte', '0010_auto_20211008_2106'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skriptasection',
            options={},
        ),
        migrations.RemoveField(
            model_name='skriptasection',
            name='section_order',
        ),
    ]
