# Generated by Django 3.2.6 on 2021-10-08 21:21

from django.db import migrations

def create_through_relations(apps, schema_editor):
    Section = apps.get_model('skripte', 'Section')
    SkriptaSection = apps.get_model('skripte', 'SkriptaSection')
    for section in Section.objects.all():
        for skripta in section.skripta.all():
            SkriptaSection(
                skripta=skripta,
                section=section
            ).save()

class Migration(migrations.Migration):

    dependencies = [
        ('skripte', '0011_auto_20211008_2121'),
    ]

    operations = [
        migrations.RunPython(create_through_relations, reverse_code=migrations.RunPython.noop),
    ]
