# Generated by Django 3.2.6 on 2021-10-08 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skripte', '0013_remove_section_skripta'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='skripta',
            field=models.ManyToManyField(blank=True, related_name='sections', through='skripte.SkriptaSection', to='skripte.Skripta'),
        ),
    ]
