# Generated by Django 3.2.6 on 2021-10-08 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skripte', '0014_section_skripta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skriptasection',
            options={'ordering': ('section_order',)},
        ),
        migrations.AddField(
            model_name='skriptasection',
            name='section_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
