# Generated by Django 3.2.6 on 2021-10-16 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_models', '0002_auto_20211016_2052'),
        ('skripte', '0015_auto_20211008_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shopify_models.page'),
        ),
    ]
