# Generated by Django 3.2.6 on 2021-10-29 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skripte', '0022_section_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='icon',
        ),
    ]
