# Generated by Django 3.2.6 on 2021-10-29 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0012_svg'),
        ('skripte', '0023_remove_section_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='media.svg'),
        ),
    ]
