# Generated by Django 3.2.6 on 2021-10-30 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0048_auto_20211008_1219'),
        ('skripte', '0024_section_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_order', models.PositiveIntegerField(default=0)),
                ('main_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_section', to='skripte.section')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_section', to='skripte.section')),
            ],
            options={
                'ordering': ('section_order',),
            },
        ),
        migrations.CreateModel(
            name='ProblemEquation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equation_order', models.PositiveIntegerField(default=0)),
                ('equation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='skripte.equation')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='problems.problem')),
            ],
            options={
                'ordering': ('equation_order',),
            },
        ),
        migrations.AddField(
            model_name='equation',
            name='problem',
            field=models.ManyToManyField(blank=True, related_name='equations', through='skripte.ProblemEquation', to='problems.Problem'),
        ),
        migrations.AddField(
            model_name='section',
            name='related_sections',
            field=models.ManyToManyField(blank=True, related_name='_skripte_section_related_sections_+', through='skripte.SectionSection', to='skripte.Section'),
        ),
    ]
