# Generated by Django 3.2.6 on 2021-10-30 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skripte', '0025_auto_20211030_1809'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sectionsection',
            old_name='section',
            new_name='related_section',
        ),
    ]
