# Generated by Django 3.2.6 on 2021-10-30 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skripte', '0026_rename_section_sectionsection_related_section'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sectionsection',
            options={'ordering': ('related_section_order',)},
        ),
        migrations.RenameField(
            model_name='sectionsection',
            old_name='section_order',
            new_name='related_section_order',
        ),
    ]
