# Generated by Django 3.2.6 on 2022-01-27 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skripte', '0031_alter_equation_related_equation'),
    ]

    operations = [
        migrations.AddField(
            model_name='skripta',
            name='label',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
