# Generated by Django 3.2.6 on 2022-01-27 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skripte', '0032_skripta_label'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skripta',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='skripta',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
