# Generated by Django 3.2.6 on 2022-03-19 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skripte', '0033_auto_20220127_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='skripta',
            name='label_short',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
