# Generated by Django 3.2.6 on 2021-09-30 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mature', '0001_initial'),
    ]

    operations = [
    ]
