# Generated by Django 3.2.6 on 2021-11-03 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0013_auto_20211103_1114'),
        ('mature', '0004_matura_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='matura',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='media.pdf'),
        ),
    ]
