# Generated by Django 3.2.6 on 2022-04-15 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mature', '0010_alter_year_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matura',
            options={'ordering': ['year', '-term']},
        ),
    ]
