# Generated by Django 3.2.6 on 2022-04-15 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mature', '0011_alter_matura_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matura',
            options={'ordering': ['year']},
        ),
    ]
