# Generated by Django 3.2.6 on 2022-01-23 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skripte', '0031_alter_equation_related_equation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cheatsheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='skripte.subject')),
            ],
        ),
        migrations.CreateModel(
            name='CheatsheetTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='Konstante')),
                ('decorator', models.TextField(blank=True, null=True)),
                ('table_order', models.PositiveIntegerField(default=0)),
                ('cheatsheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cheatsheets.cheatsheet')),
            ],
            options={
                'ordering': ('table_order',),
            },
        ),
        migrations.CreateModel(
            name='CheatsheetTableEquation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equation_order', models.PositiveIntegerField(default=0)),
                ('cheatsheet_table', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cheatsheets.cheatsheettable')),
                ('equation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='skripte.equation')),
            ],
            options={
                'ordering': ('equation_order',),
            },
        ),
        migrations.CreateModel(
            name='CheatsheetSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('decorator', models.TextField(blank=True, null=True)),
                ('section_order', models.PositiveIntegerField(default=0)),
                ('cheatsheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cheatsheets.cheatsheet')),
            ],
            options={
                'ordering': ('section_order',),
            },
        ),
        migrations.CreateModel(
            name='CheatsheetSeactionEquation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equation_order', models.PositiveIntegerField(default=0)),
                ('cheatsheet_section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cheatsheets.cheatsheetsection')),
                ('equation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='skripte.equation')),
            ],
            options={
                'ordering': ('equation_order',),
            },
        ),
    ]
