# Generated by Django 3.2.6 on 2022-05-10 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cheatsheets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheatsheetLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('css_class', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='cheatsheet',
            name='layout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cheatsheets.cheatsheetlayout'),
        ),
    ]
