# Generated by Django 3.2.6 on 2022-05-15 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0017_auto_20220411_1743'),
        ('cheatsheets', '0002_auto_20220510_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheatsheet',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='media.pdf'),
        ),
    ]
