# Generated by Django 3.2.6 on 2021-10-10 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('seo_description', models.TextField(blank=True, null=True)),
                ('seo_title', models.TextField(blank=True, null=True)),
                ('page_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(blank=True, null=True)),
                ('title', models.TextField()),
                ('seo_description', models.TextField(blank=True, null=True)),
                ('seo_title', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
