# Generated by Django 3.2.6 on 2021-10-16 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_models', '0002_auto_20211016_2052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='tempplate',
            new_name='template',
        ),
        migrations.AlterField(
            model_name='template',
            name='template_sufix',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
