# Generated by Django 3.2.6 on 2021-10-16 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_models', '0003_auto_20211016_2056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='template',
            old_name='template_sufix',
            new_name='template_suffix',
        ),
    ]
