# Generated by Django 3.2.6 on 2022-07-24 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_models', '0006_alter_product_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='template',
        ),
        migrations.DeleteModel(
            name='Template',
        ),
    ]
