# Generated by Django 3.2.6 on 2022-07-24 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_models', '0007_auto_20220724_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_suffix', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
