# Generated by Django 3.2.6 on 2022-07-24 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_models', '0008_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shopify_models.template'),
        ),
    ]
